services: 
   _defaults:
      autowire: true      # Automatically injects dependencies in your services.
      autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
      public: false
   KimaiPlugin\HttpRemoteAuthBundle\Controller\:
      resource: '../../Controller/'
      tags: ['controller.service_arguments']
   KimaiPlugin\HttpRemoteAuthBundle\Controller\HttpRemoteAuthController:
      arguments: ['@security.authentication.guard_handler','@fos_user.user_manager', '@KimaiPlugin\HttpRemoteAuthBundle\Security\HttpRemoteAuthAuthenticator']
   KimaiPlugin\HttpRemoteAuthBundle\Security\HttpRemoteAuthAuthenticator:
      arguments: ['@security.authentication.guard_handler','@logger','@fos_user.user_manager']

   
   kernel.listener.http_remote_auth:
        class: KimaiPlugin\HttpRemoteAuthBundle\Listener\HttpRemoteAuthEventListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
# security:
#     firewalls:
#         http_remote_user:
#             stateless: true
#             pattern: ^/remote_user/
#             guard:
#                 authenticators:
#                     - Plugin\HttpRemoteAuthBundle\Security\HttpRemoteAuthAuthenticator
#             access_control:
#             - { path: '^/(%app_locales%)/remote_user$', role: IS_AUTHENTICATED_ANONYMOUSLY }
       
            